EPSILON = 0.01
INTBIG = 32000
KMAX = 20
LIMITE_RESPECT = 2
LIMITE_SEVERITE = 15
PRIME_CAPACITE_FIXE = 10
PRIME_CAPACITE = 4

# Composante Moyen Terme
INTENSE_TAILLE_BEST = 3
INTENSE_TAILLE_TABU = 4
INTENSE_KMAX = 10
INTENSE_LIMITE_RESPECT = 2